/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sesion09ejemplo01;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class pantalla extends javax.swing.JFrame {

    /**
     * Creates new form pantalla
     */
    float posx = 400;
    float posYbalita = 0;
    boolean balitaExiste = false;
    int dir = 1;

    public pantalla() {

        initComponents();
        balita.setVisible(false);

        Timer timer = new Timer(95, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                if (posx >= 410) {
                    dir = -1;
                }
                if (posx <= 0) {
                    dir = 1;
                }

                posx = posx + 5 * dir;

                posYbalita = posYbalita - 5;
                enemigo.setBounds((int) posx, enemigo.getY(),
                        enemigo.getWidth(),
                        enemigo.getHeight());

                if (balitaExiste) {
                    balita.setBounds(balita.getX(), (int) posYbalita,
                            balita.getWidth(),
                            balita.getHeight());
                    System.out.println(balita.getY());
                }
                if (posYbalita <= 10) {
                    //balita.setVisible(false);
                    balitaExiste = false;
                    posYbalita = 0;
                }
                if ((balita.getY() <= enemigo.getY() + 50 && balita.getY() > 20)
                        && (balita.getX() >= enemigo.getX() - 80)
                        && (balita.getX() <= enemigo.getX() + 80)) {
                    balitaExiste = false;
                    enemigo.setVisible(false);
                    balita.setVisible(false);

                    // Mensaje
                    JOptionPane.showMessageDialog(enemigo, 
                            "¡Ganaste la partida!");

                }
            }
        });

        // Inicia el temporizador
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tanque = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        balita = new javax.swing.JPanel();
        enemigo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanque.setBackground(new java.awt.Color(153, 255, 255));
        tanque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capturatanqueeee1.jpg"))); // NOI18N
        tanque.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 90, 80));

        getContentPane().add(tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 70, -1));

        balita.setBackground(new java.awt.Color(255, 255, 0));
        balita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout balitaLayout = new javax.swing.GroupLayout(balita);
        balita.setLayout(balitaLayout);
        balitaLayout.setHorizontalGroup(
            balitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        balitaLayout.setVerticalGroup(
            balitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        getContentPane().add(balita, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 10, 20));

        enemigo.setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CapturaENEMIGOO1.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout enemigoLayout = new javax.swing.GroupLayout(enemigo);
        enemigo.setLayout(enemigoLayout);
        enemigoLayout.setHorizontalGroup(
            enemigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemigoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemigoLayout.setVerticalGroup(
            enemigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(enemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capturafondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_SPACE
                || evt.getKeyCode() == KeyEvent.VK_W) {
            if (balitaExiste == true) {

            } else {
                posYbalita = 380;
                balita.setBounds(tanque.getX() + 40, (int) posYbalita,
                        10, 20);
                balitaExiste = true;
                balita.setVisible(true);
            }

        }

        //if(evt.getKeyCode() == KeyEvent.VK_DOWN
        //        ||evt.getKeyCode() == KeyEvent.VK_S){
        //    tanque.setBounds(tanque.getX(), tanque.getY() + 5,
        //tanque.getWidth(), tanque.getHeight());
        //}
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT
                || evt.getKeyCode() == KeyEvent.VK_D) {
            tanque.setBounds(tanque.getX() + 5, tanque.getY(),
                    tanque.getWidth(), tanque.getHeight());
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT
                || evt.getKeyCode() == KeyEvent.VK_A) {
            tanque.setBounds(tanque.getX() - 5, tanque.getY(),
                    tanque.getWidth(), tanque.getHeight());
        }

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel balita;
    private javax.swing.JPanel enemigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel tanque;
    // End of variables declaration//GEN-END:variables
}
